import Head from 'next/head';
import Script from 'next/script';

import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Script id="mobile-youtube-autoplay-test">
                {`
                    var tag = document.createElement('script');
                    // 2. This code loads the IFrame Player API code asynchronously.

                    tag.src = "https://www.youtube.com/iframe_api";
                    var firstScriptTag = document.getElementsByTagName('script')[0];
                    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                    // 3. This function creates an <iframe> (and YouTube player)
                    //    after the API code downloads.
                    var player;
                    function onYouTubeIframeAPIReady() {
                      player = new YT.Player('player', {
                        width: '100%',
                        videoId: 'Tw0J7W33MpM',
                        playerVars: { 'autoplay': 1, 'playsinline': 1 },
                        events: {
                          'onReady': onPlayerReady
                        }
                      });
                    }

                    // 4. The API will call this function when the video player is ready.
                    function onPlayerReady(event) {
                      event.target.mute();
                      event.target.playVideo();
                    }`}
            </Script>

            <main className={styles.main}>
                <div id="player"></div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
